//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateData.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenerateData.Resources.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin account.
        /// </summary>
        internal static string AdminAccount {
            get {
                return ResourceManager.GetString("AdminAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you&apos;re not allowed to change the number of generated rows..
        /// </summary>
        internal static string CannotChangeNumRows {
            get {
                return ResourceManager.GetString("CannotChangeNumRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete 1 Data Set.
        /// </summary>
        internal static string Delete1DataSet {
            get {
                return ResourceManager.GetString("Delete1DataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete %1 Data Sets.
        /// </summary>
        internal static string DeleteNDataSets {
            get {
                return ResourceManager.GetString("DeleteNDataSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your user account details below..
        /// </summary>
        internal static string EnterUserAccountDetails {
            get {
                return ResourceManager.GetString("EnterUserAccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ack! There was an error in the Export Type&apos;s validate() function. Sorry, we can&apos;t proceed - call a developer!.
        /// </summary>
        internal static string ExportTypeValidateError {
            get {
                return ResourceManager.GetString("ExportTypeValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation error.
        /// </summary>
        internal static string InstallationError {
            get {
                return ResourceManager.GetString("InstallationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number of results..
        /// </summary>
        internal static string InvalidNumResults {
            get {
                return ResourceManager.GetString("InvalidNumResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last edited.
        /// </summary>
        internal static string LastEdited {
            get {
                return ResourceManager.GetString("LastEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last saved.
        /// </summary>
        internal static string LastSaved {
            get {
                return ResourceManager.GetString("LastSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to Data Set.
        /// </summary>
        internal static string LinkToDataSet {
            get {
                return ResourceManager.GetString("LinkToDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, nothing to generate! Enter some data to be generated..
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Types found.
        /// </summary>
        internal static string NoDataTypesFound {
            get {
                return ResourceManager.GetString("NoDataTypesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Export Types found.
        /// </summary>
        internal static string NoExportTypesFound {
            get {
                return ResourceManager.GetString("NoExportTypesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the number of rows to add..
        /// </summary>
        internal static string NoNumRows {
            get {
                return ResourceManager.GetString("NoNumRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No options available..
        /// </summary>
        internal static string NoOptionsAvailable {
            get {
                return ResourceManager.GetString("NoOptionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not saved.
        /// </summary>
        internal static string NotSaved {
            get {
                return ResourceManager.GetString("NotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you&apos;re limited to generating &lt;b&gt;%1&lt;/b&gt; rows at a time. Click generate to continue..
        /// </summary>
        internal static string NumRowsTooLarge {
            get {
                return ResourceManager.GetString("NumRowsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm.
        /// </summary>
        internal static string PleaseConfirm {
            get {
                return ResourceManager.GetString("PleaseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all.
        /// </summary>
        internal static string PleaseEnterAll {
            get {
                return ResourceManager.GetString("PleaseEnterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Page.
        /// </summary>
        internal static string RefreshPage {
            get {
                return ResourceManager.GetString("RefreshPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Titles.
        /// </summary>
        internal static string RowLabelPlural {
            get {
                return ResourceManager.GetString("RowLabelPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show data format options.
        /// </summary>
        internal static string ShowDataFormatOptions {
            get {
                return ResourceManager.GetString("ShowDataFormatOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an account with that email address already exists..
        /// </summary>
        internal static string ValidationAccountAlreadyExists {
            get {
                return ResourceManager.GetString("ValidationAccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphanumeric and underscore characters only, please..
        /// </summary>
        internal static string ValidationInvalidChars {
            get {
                return ResourceManager.GetString("ValidationInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        internal static string ValidationInvalidEmail {
            get {
                return ResourceManager.GetString("ValidationInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to do this..
        /// </summary>
        internal static string ValidationInvalidPermissions {
            get {
                return ResourceManager.GetString("ValidationInvalidPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your database hostname..
        /// </summary>
        internal static string ValidationNoDbHostname {
            get {
                return ResourceManager.GetString("ValidationNoDbHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your database name..
        /// </summary>
        internal static string ValidationNoDbName {
            get {
                return ResourceManager.GetString("ValidationNoDbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address..
        /// </summary>
        internal static string ValidationNoEmail {
            get {
                return ResourceManager.GetString("ValidationNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your first name..
        /// </summary>
        internal static string ValidationNoFirstName {
            get {
                return ResourceManager.GetString("ValidationNoFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your last name..
        /// </summary>
        internal static string ValidationNoLastName {
            get {
                return ResourceManager.GetString("ValidationNoLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your MySQL username..
        /// </summary>
        internal static string ValidationNoMysqlUsername {
            get {
                return ResourceManager.GetString("ValidationNoMysqlUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password..
        /// </summary>
        internal static string ValidationNoPassword {
            get {
                return ResourceManager.GetString("ValidationNoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t appear to be logged in. Please try logging in again..
        /// </summary>
        internal static string ValidationNotLoggedIn {
            get {
                return ResourceManager.GetString("ValidationNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
