//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateData.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class tmp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal tmp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenerateData.Resources.tmp", typeof(tmp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes you need fake data for things like testing software, populating databases and creating realistic-looking mockups. For text, we have &lt;i&gt;lorem ipsum&lt;/i&gt;; but for everything else...? This tool was written to provide a quick and simple way to let you generate large volumes of custom data in whatever format you require..
        /// </summary>
        internal static string AboutPara1 {
            get {
                return ResourceManager.GetString("AboutPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Generate&lt;/b&gt; page contains the entire script: just fill in the various fields in the page to construct the data set you&apos;re interested in, then click the Generate button. And hey presto! Easy, huh?.
        /// </summary>
        internal static string AboutPara2 {
            get {
                return ResourceManager.GetString("AboutPara2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The out-the-box script contains the sort of functionality you generally need. But nothing&apos;s ever complete - maybe you need to generate random esoteric math equations, pull random tweets or display random images from Flickr with the word &quot;Red-backed=&quot;&quot; vole=&quot;&quot;&quot; in the title. Who knows. Everyone&apos;s use-case is different..
        /// </summary>
        internal static string AboutPara3 {
            get {
                return ResourceManager.GetString("AboutPara3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this in mind, the new version of the script (3.0.0+) was designed to be fully extensible: developers can write their own Data Types to generate new types of random data, and even customize the Export Types - i.e. the format in which the data is output. For people interested in generating more accurate localized geographical data, they can also add new Country plugins that supply region names (states, provinces, territories etc), city names and postal/zip code formats for their country of choice..
        /// </summary>
        internal static string AboutPara4 {
            get {
                return ResourceManager.GetString("AboutPara4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information on how to extend it, visit the &lt;a href=&quot;docs/&quot;&gt;developer documentation&lt;/a&gt;..
        /// </summary>
        internal static string AboutPara5 {
            get {
                return ResourceManager.GetString("AboutPara5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What &lt;i&gt;is&lt;/i&gt; this thing?.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Created.
        /// </summary>
        internal static string AccountCreated {
            get {
                return ResourceManager.GetString("AccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account has been created for you..
        /// </summary>
        internal static string AccountCreatedMsg {
            get {
                return ResourceManager.GetString("AccountCreatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Info.
        /// </summary>
        internal static string AccountInfo {
            get {
                return ResourceManager.GetString("AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        internal static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type.
        /// </summary>
        internal static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been updated..
        /// </summary>
        internal static string AccountUpdated {
            get {
                return ResourceManager.GetString("AccountUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin account.
        /// </summary>
        internal static string AdminAccount {
            get {
                return ResourceManager.GetString("AdminAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A few links.
        /// </summary>
        internal static string AFewLinks {
            get {
                return ResourceManager.GetString("AFewLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africa.
        /// </summary>
        internal static string Africa {
            get {
                return ResourceManager.GetString("Africa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All countries.
        /// </summary>
        internal static string AllCountries {
            get {
                return ResourceManager.GetString("AllCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Data Type plugins.
        /// </summary>
        internal static string AllDataTypePlugins {
            get {
                return ResourceManager.GetString("AllDataTypePlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Export Type plugins.
        /// </summary>
        internal static string AllExportTypePlugins {
            get {
                return ResourceManager.GetString("AllExportTypePlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous admin account.
        /// </summary>
        internal static string AnonymousAdminAccount {
            get {
                return ResourceManager.GetString("AnonymousAdminAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asia.
        /// </summary>
        internal static string Asia {
            get {
                return ResourceManager.GetString("Asia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you&apos;re not allowed to change the number of generated rows..
        /// </summary>
        internal static string CannotChangeNumRows {
            get {
                return ResourceManager.GetString("CannotChangeNumRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central America.
        /// </summary>
        internal static string CentralAmerica {
            get {
                return ResourceManager.GetString("CentralAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the Page.
        /// </summary>
        internal static string ClearThePage {
            get {
                return ResourceManager.GetString("ClearThePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this form?.
        /// </summary>
        internal static string ConfirmDeleteForm {
            get {
                return ResourceManager.GetString("ConfirmDeleteForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user account?.
        /// </summary>
        internal static string ConfirmDeleteUserAccount {
            get {
                return ResourceManager.GetString("ConfirmDeleteUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the page?.
        /// </summary>
        internal static string ConfirmEmptyForm {
            get {
                return ResourceManager.GetString("ConfirmEmptyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country-Specific Data.
        /// </summary>
        internal static string CountrySpecificData {
            get {
                return ResourceManager.GetString("CountrySpecificData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account &amp;raquo;.
        /// </summary>
        internal static string CreateAccountRightarrow {
            get {
                return ResourceManager.GetString("CreateAccountRightarrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Data.
        /// </summary>
        internal static string CreditCardData {
            get {
                return ResourceManager.GetString("CreditCardData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Info.
        /// </summary>
        internal static string DatabaseInfo {
            get {
                return ResourceManager.GetString("DatabaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Created.
        /// </summary>
        internal static string DataCreated {
            get {
                return ResourceManager.GetString("DataCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Format.
        /// </summary>
        internal static string DataFormat {
            get {
                return ResourceManager.GetString("DataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Set.
        /// </summary>
        internal static string DataSet {
            get {
                return ResourceManager.GetString("DataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where you define exactly what kind of data you want to generate. Try filling in a row or two and click the Generate button. You&apos;ll get the hang of it pretty fast..
        /// </summary>
        internal static string DataSetHelp {
            get {
                return ResourceManager.GetString("DataSetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Set Name.
        /// </summary>
        internal static string DataSetName {
            get {
                return ResourceManager.GetString("DataSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        internal static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date account created.
        /// </summary>
        internal static string DateAccountCreated {
            get {
                return ResourceManager.GetString("DateAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        internal static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter form name here.
        /// </summary>
        internal static string DefaultSaveFormEmpty {
            get {
                return ResourceManager.GetString("DefaultSaveFormEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        internal static string Del {
            get {
                return ResourceManager.GetString("Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete 1 Data Set.
        /// </summary>
        internal static string Delete1DataSet {
            get {
                return ResourceManager.GetString("Delete1DataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete %1 Data Sets.
        /// </summary>
        internal static string DeleteNDataSets {
            get {
                return ResourceManager.GetString("DeleteNDataSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEL.
        /// </summary>
        internal static string DelUc {
            get {
                return ResourceManager.GetString("DelUc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        internal static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer doc.
        /// </summary>
        internal static string DeveloperDoc {
            get {
                return ResourceManager.GetString("DeveloperDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following sections lets you fine-tune what you see in your javascript console for development purposes..
        /// </summary>
        internal static string DeveloperIntro {
            get {
                return ResourceManager.GetString("DeveloperIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate!.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string EmailC {
            get {
                return ResourceManager.GetString("EmailC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to send the email notification..
        /// </summary>
        internal static string EmailNotSent {
            get {
                return ResourceManager.GetString("EmailNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email the user their login information.
        /// </summary>
        internal static string EmailUserLoginInfo {
            get {
                return ResourceManager.GetString("EmailUserLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Form.
        /// </summary>
        internal static string EmptyForm {
            get {
                return ResourceManager.GetString("EmptyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your user account details below..
        /// </summary>
        internal static string EnterUserAccountDetails {
            get {
                return ResourceManager.GetString("EnterUserAccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        internal static string Europe {
            get {
                return ResourceManager.GetString("Europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        internal static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section lets you control the format of your generated data. Each format may provide different options to let you tailor the output to exactly what you want..
        /// </summary>
        internal static string ExportTypesHelp {
            get {
                return ResourceManager.GetString("ExportTypesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ack! There was an error in the Export Type&apos;s validate() function. Sorry, we can&apos;t proceed - call a developer!.
        /// </summary>
        internal static string ExportTypeValidateError {
            get {
                return ResourceManager.GetString("ExportTypeValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend it.
        /// </summary>
        internal static string ExtendId {
            get {
                return ResourceManager.GetString("ExtendId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend it.
        /// </summary>
        internal static string ExtendIt {
            get {
                return ResourceManager.GetString("ExtendIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occurred..
        /// </summary>
        internal static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fork the code on github.
        /// </summary>
        internal static string ForkOnGithub {
            get {
                return ResourceManager.GetString("ForkOnGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fork this project on Github.
        /// </summary>
        internal static string ForkThisProjectOnGithub {
            get {
                return ResourceManager.GetString("ForkThisProjectOnGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form has been deleted..
        /// </summary>
        internal static string FormDeleted {
            get {
                return ResourceManager.GetString("FormDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form already exists. Do you want to overwrite it?.
        /// </summary>
        internal static string FormExistsOverwriteConfirmation {
            get {
                return ResourceManager.GetString("FormExistsOverwriteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we couldn&amp;#39;t delete this form. Re-log in and try again..
        /// </summary>
        internal static string FormNotDeleted {
            get {
                return ResourceManager.GetString("FormNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your form has been saved..
        /// </summary>
        internal static string FormSaved {
            get {
                return ResourceManager.GetString("FormSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        internal static string Forums {
            get {
                return ResourceManager.GetString("Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated &lt;span id=&quot;gdGenerateCount&quot;&gt;&lt;/span&gt; of &lt;span id=&quot;gdGenerateTotal&quot;&gt;&lt;/span&gt; results.
        /// </summary>
        internal static string GeneratedXOfYResults {
            get {
                return ResourceManager.GetString("GeneratedXOfYResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate in-page.
        /// </summary>
        internal static string GenerateInPage {
            get {
                return ResourceManager.GetString("GenerateInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator.
        /// </summary>
        internal static string Generator {
            get {
                return ResourceManager.GetString("Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo.
        /// </summary>
        internal static string Geo {
            get {
                return ResourceManager.GetString("Geo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the website.
        /// </summary>
        internal static string GotoWebsite {
            get {
                return ResourceManager.GetString("GotoWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide data format options.
        /// </summary>
        internal static string HideDataFormatOptions {
            get {
                return ResourceManager.GetString("HideDataFormatOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide error.
        /// </summary>
        internal static string HideError {
            get {
                return ResourceManager.GetString("HideError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of your database connection. Often it&apos;s just &lt;i&gt;localhost&lt;/i&gt;, but sometimes it&apos;s something like &lt;i&gt;mysql.yoursite.com&lt;/i&gt;..
        /// </summary>
        internal static string HostnameDesc {
            get {
                return ResourceManager.GetString("HostnameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Data.
        /// </summary>
        internal static string HumanData {
            get {
                return ResourceManager.GetString("HumanData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info and Stats.
        /// </summary>
        internal static string InfoAndStats {
            get {
                return ResourceManager.GetString("InfoAndStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation error.
        /// </summary>
        internal static string InstallationError {
            get {
                return ResourceManager.GetString("InstallationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The script was unable to create your &lt;b&gt;settings.php&lt;/b&gt; file..
        /// </summary>
        internal static string InstallationFailedCreateSettingsFile {
            get {
                return ResourceManager.GetString("InstallationFailedCreateSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to connect to the database using the information you supplied. The error message the database returned is: &lt;i&gt;{\$db_connectionError}&lt;/i&gt;.
        /// </summary>
        internal static string InstallInvalidDbInfo {
            get {
                return ResourceManager.GetString("InstallInvalidDbInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your database name and login information. Although we were able to connect to the database host, we could not connect to the database. The error message the database returned is: &lt;i&gt;{\$db_select_error}&lt;/i&gt;.
        /// </summary>
        internal static string InstallNoDbConnection {
            get {
                return ResourceManager.GetString("InstallNoDbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Account ID is not valid..
        /// </summary>
        internal static string InvalidAccountId {
            get {
                return ResourceManager.GetString("InvalidAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&amp;#39;s a problem with the custom XML markup you entered. Please consult the user documentation for more information..
        /// </summary>
        internal static string InvalidCustomXml {
            get {
                return ResourceManager.GetString("InvalidCustomXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number of results..
        /// </summary>
        internal static string InvalidNumResults {
            get {
                return ResourceManager.GetString("InvalidNumResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, that password is not correct. Please try again..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database column names can only alphanumeric characters and must begin with a letter. Please fix the following rows:.
        /// </summary>
        internal static string InvalidTableNames {
            get {
                return ResourceManager.GetString("InvalidTableNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last edited.
        /// </summary>
        internal static string LastEdited {
            get {
                return ResourceManager.GetString("LastEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Logged In.
        /// </summary>
        internal static string LastLoggedIn {
            get {
                return ResourceManager.GetString("LastLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        internal static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last saved.
        /// </summary>
        internal static string LastSaved {
            get {
                return ResourceManager.GetString("LastSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest project news.
        /// </summary>
        internal static string LatestProjectNews {
            get {
                return ResourceManager.GetString("LatestProjectNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit pub/sub console messages to specific modules:.
        /// </summary>
        internal static string LimitPubSubConsoleMessages {
            get {
                return ResourceManager.GetString("LimitPubSubConsoleMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to Data Set.
        /// </summary>
        internal static string LinkToDataSet {
            get {
                return ResourceManager.GetString("LinkToDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to this Data Set.
        /// </summary>
        internal static string LinkToThisDataSet {
            get {
                return ResourceManager.GetString("LinkToThisDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List console.warn() events.
        /// </summary>
        internal static string ListConsoleWarnEvents {
            get {
                return ResourceManager.GetString("ListConsoleWarnEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List &lt;b&gt;core&lt;/b&gt; events.
        /// </summary>
        internal static string ListCoreEvents {
            get {
                return ResourceManager.GetString("ListCoreEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List module &lt;b&gt;publish&lt;/b&gt; events.
        /// </summary>
        internal static string ListModulePublishEvents {
            get {
                return ResourceManager.GetString("ListModulePublishEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List module &lt;b&gt;subscribe&lt;/b&gt; events.
        /// </summary>
        internal static string ListModuleSubscribeEvents {
            get {
                return ResourceManager.GetString("ListModuleSubscribeEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOAD.
        /// </summary>
        internal static string LoadUc {
            get {
                return ResourceManager.GetString("LoadUc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login URL:.
        /// </summary>
        internal static string LoginUrlC {
            get {
                return ResourceManager.GetString("LoginUrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand that to share this Data Set, I need to make it public..
        /// </summary>
        internal static string MakeDataSetPublicAgreement {
            get {
                return ResourceManager.GetString("MakeDataSetPublicAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math.
        /// </summary>
        internal static string Math {
            get {
                return ResourceManager.GetString("Math", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following rows have missing node names:.
        /// </summary>
        internal static string MissingNodeName {
            get {
                return ResourceManager.GetString("MissingNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following rows have missing table column names:.
        /// </summary>
        internal static string MissingTableName {
            get {
                return ResourceManager.GetString("MissingTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New window/tab.
        /// </summary>
        internal static string NewWindowOrTab {
            get {
                return ResourceManager.GetString("NewWindowOrTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, that account wasn&apos;t found..
        /// </summary>
        internal static string NoAccountFound {
            get {
                return ResourceManager.GetString("NoAccountFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No additional export type settings..
        /// </summary>
        internal static string NoAdditionalExportTypeSettings {
            get {
                return ResourceManager.GetString("NoAdditionalExportTypeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the CSV delimiter..
        /// </summary>
        internal static string NoCsvDelimiter {
            get {
                return ResourceManager.GetString("NoCsvDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, nothing to generate! Enter some data to be generated..
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Types found.
        /// </summary>
        internal static string NoDataTypesFound {
            get {
                return ResourceManager.GetString("NoDataTypesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No examples available..
        /// </summary>
        internal static string NoExamplesAvailable {
            get {
                return ResourceManager.GetString("NoExamplesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Export Types found.
        /// </summary>
        internal static string NoExportTypesFound {
            get {
                return ResourceManager.GetString("NoExportTypesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NoFormName {
            get {
                return ResourceManager.GetString("NoFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You know this is, like, the 21st century? The Data Generator script relies heavily on javascript - things just plain won&apos;t work without it. You&amp;#39;ll need to enable it in your browser then refresh this page..
        /// </summary>
        internal static string NoJsBlurb {
            get {
                return ResourceManager.GetString("NoJsBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the number of rows to add..
        /// </summary>
        internal static string NoNumRows {
            get {
                return ResourceManager.GetString("NoNumRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No options available..
        /// </summary>
        internal static string NoOptionsAvailable {
            get {
                return ResourceManager.GetString("NoOptionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North America.
        /// </summary>
        internal static string NorthAmerica {
            get {
                return ResourceManager.GetString("NorthAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any saved data sets..
        /// </summary>
        internal static string NoSavedDataSets {
            get {
                return ResourceManager.GetString("NoSavedDataSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your settings have been updated..
        /// </summary>
        internal static string NotifySettingsUpdated {
            get {
                return ResourceManager.GetString("NotifySettingsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not saved.
        /// </summary>
        internal static string NotSaved {
            get {
                return ResourceManager.GetString("NotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user accounts defined..
        /// </summary>
        internal static string NoUserAccountsDefined {
            get {
                return ResourceManager.GetString("NoUserAccountsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        internal static string Numeric {
            get {
                return ResourceManager.GetString("Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated.
        /// </summary>
        internal static string NumRecordsGenerated {
            get {
                return ResourceManager.GetString("NumRecordsGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num Results.
        /// </summary>
        internal static string NumResults {
            get {
                return ResourceManager.GetString("NumResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you&apos;re limited to generating &lt;b&gt;%1&lt;/b&gt; rows at a time. Click generate to continue..
        /// </summary>
        internal static string NumRowsTooLarge {
            get {
                return ResourceManager.GetString("NumRowsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num Saved Data Sets.
        /// </summary>
        internal static string NumSavedDataSets {
            get {
                return ResourceManager.GetString("NumSavedDataSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceania.
        /// </summary>
        internal static string Oceania {
            get {
                return ResourceManager.GetString("Oceania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string PasswordC {
            get {
                return ResourceManager.GetString("PasswordC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You only need to fill the password fields in if you want to change it..
        /// </summary>
        internal static string PasswordChangeNote {
            get {
                return ResourceManager.GetString("PasswordChangeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset and you have been emailed the new password..
        /// </summary>
        internal static string PasswordResetComplete {
            get {
                return ResourceManager.GetString("PasswordResetComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. You may use the following password to log in: %1.
        /// </summary>
        internal static string PasswordResetEmailContent1 {
            get {
                return ResourceManager.GetString("PasswordResetEmailContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please change it once you&apos;ve logged in..
        /// </summary>
        internal static string PasswordResetEmailContent2 {
            get {
                return ResourceManager.GetString("PasswordResetEmailContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm.
        /// </summary>
        internal static string PleaseConfirm {
            get {
                return ResourceManager.GetString("PleaseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all.
        /// </summary>
        internal static string PleaseEnterAll {
            get {
                return ResourceManager.GetString("PleaseEnterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of the new Data Set..
        /// </summary>
        internal static string PleaseEnterDataSetName {
            get {
                return ResourceManager.GetString("PleaseEnterDataSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix the following errors and resubmit:.
        /// </summary>
        internal static string PleaseFixErrors {
            get {
                return ResourceManager.GetString("PleaseFixErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        internal static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any time you add or remove a plugin, you need to reset the plugins. This will update the database and ensure you can access the plugins you require..
        /// </summary>
        internal static string PluginsIntro {
            get {
                return ResourceManager.GetString("PluginsIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt to download.
        /// </summary>
        internal static string PromptToDownload {
            get {
                return ResourceManager.GetString("PromptToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public?.
        /// </summary>
        internal static string PublicQ {
            get {
                return ResourceManager.GetString("PublicQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the developer documentation.
        /// </summary>
        internal static string ReadDeveloperDoc {
            get {
                return ResourceManager.GetString("ReadDeveloperDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter password.
        /// </summary>
        internal static string ReenterPassword {
            get {
                return ResourceManager.GetString("ReenterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Page.
        /// </summary>
        internal static string RefreshPage {
            get {
                return ResourceManager.GetString("RefreshPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate.
        /// </summary>
        internal static string Regenerate {
            get {
                return ResourceManager.GetString("Regenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset plugins.
        /// </summary>
        internal static string ResetPlugins {
            get {
                return ResourceManager.GetString("ResetPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;You have bundling/minification enabled&lt;/b&gt;. After clicking this button you will need to run &lt;i&gt;grunt&lt;/i&gt; to recreate the bundles. For more information &lt;a href=&quot;http://benkeen.github.io/generatedata/developer.html#bundling&quot; target=&quot;_blank&quot;&gt;read this documentation page&lt;/a&gt;. If you have any problems, you may want to turn off bundling..
        /// </summary>
        internal static string ResetPluginsWithBundling {
            get {
                return ResourceManager.GetString("ResetPluginsWithBundling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Type.
        /// </summary>
        internal static string ResultType {
            get {
                return ResourceManager.GetString("ResultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Title.
        /// </summary>
        internal static string RowLabel {
            get {
                return ResourceManager.GetString("RowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Titles.
        /// </summary>
        internal static string RowLabelPlural {
            get {
                return ResourceManager.GetString("RowLabelPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rows.
        /// </summary>
        internal static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows Generated.
        /// </summary>
        internal static string RowsGenerated {
            get {
                return ResourceManager.GetString("RowsGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row(s).
        /// </summary>
        internal static string RowSp {
            get {
                return ResourceManager.GetString("RowSp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-&lt;i&gt;nied&lt;/i&gt;. In order to share this Data Set with other people, you need to save it first..
        /// </summary>
        internal static string SaveDataSetToLink {
            get {
                return ResourceManager.GetString("SaveDataSetToLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string SaveUc {
            get {
                return ResourceManager.GetString("SaveUc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, hold on for a second. The script is thinking..
        /// </summary>
        internal static string ScriptThinking {
            get {
                return ResourceManager.GetString("ScriptThinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;See help dialog..
        /// </summary>
        internal static string SeeHelpDialog {
            get {
                return ResourceManager.GetString("SeeHelpDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Data Type.
        /// </summary>
        internal static string SelectDataType {
            get {
                return ResourceManager.GetString("SelectDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings file already exists. For new installations, the settings.php shouldn&apos;t exist. Either delete it and continue the installation script or try loading the script again with the existing settings file values..
        /// </summary>
        internal static string SettingsFileExists {
            get {
                return ResourceManager.GetString("SettingsFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show data format options.
        /// </summary>
        internal static string ShowDataFormatOptions {
            get {
                return ResourceManager.GetString("ShowDataFormatOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South America.
        /// </summary>
        internal static string SouthAmerica {
            get {
                return ResourceManager.GetString("SouthAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Column.
        /// </summary>
        internal static string TableColumn {
            get {
                return ResourceManager.GetString("TableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section lets you control what country-specific data should be included in your generated data sets. The values you select here affect certain Data Types that you may select, such as &lt;i&gt;Region&lt;/i&gt;, &lt;i&gt;Postal/Zip&lt;/i&gt; and &lt;i&gt;Country&lt;/i&gt;.&lt;/p&gt;&lt;p&gt;
        ///		To give you a better idea of what this means, try selecting the &lt;i&gt;Region&lt;/i&gt; Data Type for one of your rows in the Data Set section, then add / remove countries from the Country-Specific Data section. You&apos;ll see that the row options that appear are directly aff [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TipCountryData {
            get {
                return ResourceManager.GetString("TipCountryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total rows generated.
        /// </summary>
        internal static string TotalRowsGenerated {
            get {
                return ResourceManager.GetString("TotalRowsGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Account.
        /// </summary>
        internal static string UpdateAccount {
            get {
                return ResourceManager.GetString("UpdateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Settings.
        /// </summary>
        internal static string UpdateSettings {
            get {
                return ResourceManager.GetString("UpdateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom XML format.
        /// </summary>
        internal static string UseCustomXmlFormat {
            get {
                return ResourceManager.GetString("UseCustomXmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        internal static string UserAccount {
            get {
                return ResourceManager.GetString("UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section lets you create any number of users accounts to allow people access to the script. Only you are able to create or delete accounts..
        /// </summary>
        internal static string UserAccountSectionIntro {
            get {
                return ResourceManager.GetString("UserAccountSectionIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we were unable to identify you..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an account with that email address already exists..
        /// </summary>
        internal static string ValidationAccountAlreadyExists {
            get {
                return ResourceManager.GetString("ValidationAccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphanumeric and underscore characters only, please..
        /// </summary>
        internal static string ValidationInvalidChars {
            get {
                return ResourceManager.GetString("ValidationInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        internal static string ValidationInvalidEmail {
            get {
                return ResourceManager.GetString("ValidationInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permissions to do this..
        /// </summary>
        internal static string ValidationInvalidPermissions {
            get {
                return ResourceManager.GetString("ValidationInvalidPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your database hostname..
        /// </summary>
        internal static string ValidationNoDbHostname {
            get {
                return ResourceManager.GetString("ValidationNoDbHostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your database name..
        /// </summary>
        internal static string ValidationNoDbName {
            get {
                return ResourceManager.GetString("ValidationNoDbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address..
        /// </summary>
        internal static string ValidationNoEmail {
            get {
                return ResourceManager.GetString("ValidationNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your first name..
        /// </summary>
        internal static string ValidationNoFirstName {
            get {
                return ResourceManager.GetString("ValidationNoFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your last name..
        /// </summary>
        internal static string ValidationNoLastName {
            get {
                return ResourceManager.GetString("ValidationNoLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your MySQL username..
        /// </summary>
        internal static string ValidationNoMysqlUsername {
            get {
                return ResourceManager.GetString("ValidationNoMysqlUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password..
        /// </summary>
        internal static string ValidationNoPassword {
            get {
                return ResourceManager.GetString("ValidationNoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t appear to be logged in. Please try logging in again..
        /// </summary>
        internal static string ValidationNotLoggedIn {
            get {
                return ResourceManager.GetString("ValidationNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data set name here....
        /// </summary>
        internal static string YourDataSetNameHere {
            get {
                return ResourceManager.GetString("YourDataSetNameHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Data Sets.
        /// </summary>
        internal static string YourDataSets {
            get {
                return ResourceManager.GetString("YourDataSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip?.
        /// </summary>
        internal static string ZipQ {
            get {
                return ResourceManager.GetString("ZipQ", resourceCulture);
            }
        }
    }
}
